### PR TITLE
[Refactor] Faster instantiation

### PR DESCRIPTION
**Pull request by vmoens**

### CODE REVIEW

**Comment by vmoens** [comment]
woohoo! +112% on creation speed!
@albertbou92 @matteobettini @BY571 @skandermolla
In practice, for torchrl it's a >10% further speedup on data collection speed (but also impacts all other modules)
Can anyone review this?

**Comment by albertbou92** [comment]
I see, so defining directly the attributes as class-level attributes is faster at runtime than doing attribute assignment in the __new__ method, is that it?

**Comment by vmoens** [comment]
Yes that and removing slots

**Review by albertbou92 — APPROVED** [review]

**Comment by albertbou92** [comment]
> Yes that and removing slots

looking forward to see how it affects torchrl speed! :)

**Pull request merged**
